### ISSUE TITLE
Would you help me to integrate phpsocket server with socket io JS client

### ISSUE THREAD

**Issue by faywong** [RickySu/phpsocket.io#9]
The JS client: http://socket.io/docs/client-api/

I start an the example/server.php in cli mode as server(listen at 127.0.0.1:8080, in order to run it, i configure php to include extension "event.so")

Then i use the JS client to communicate with the server like this(similar to http://socket.io/demos/chat/):
"
  var socket = io('http://127.0.0.1:8080/');
"
But the JS client(the above website's demo only involves Nodejs server & js client) doesn't work as i expect, the JS client keep polling a unavailable resource(maybe is hardcoded in socket.io.{version}.js, i haven't figure it out yet):

![image](https://cloud.githubusercontent.com/assets/1934627/4320995/2c40bf18-3f3c-11e4-9617-181f260bb654.png)

Thanks in advance,
faywong

**Comment by douggr** [comment]
@faywong you should use `var socket = io.connect('127.0.0.1:8080');` instead.

Anyway, looks like you are using `socket.io@1.x`, it will not work within
`phpsocket.io@current` because `PHPSocketIO\Protocol\Handshake` is hardcoded
to use and/or parse the *exact* parameters provided by `socket.io@0.9.x`.

You now have 2 options:
  - Patch `PHPSocketIO\Protocol\Handshake` **or**
  - Use socket.io@0.9.x

**Comment by ameoba32** [comment]
Same problem here, no fix yet? :)  .

**Comment by faywong** [comment]
Thx for your clarify.
